// pkg/view/src/pages/auth/connect.tsx
import { createSignal, Show } from "solid-js";
import { useLocation, useSearchParams } from "@solidjs/router";
import { getAtk, useUserinfo } from "../../stores/userinfo.tsx";
import { request } from "../../scripts/request.ts";

export default function OauthConnectPage() {
  const [title, setTitle] = createSignal("Connect Third-party");
  const [subtitle, setSubtitle] = createSignal("Via your Goatpass account");

  const [error, setError] = createSignal<string | null>(null);
  const [status, setStatus] = createSignal("Handshaking...");
  const [loading, setLoading] = createSignal(true);

  const [client, setClient] = createSignal<any>(null);

  const [searchParams] = useSearchParams();

  const userinfo = useUserinfo();
  const location = useLocation();

  async function preConnect() {
    const res = await request(`/api/auth/o/connect${location.search}`, {
      headers: { "Authorization": `Bearer ${getAtk()}` }
    });

    if (res.status !== 200) {
      setError(await res.text());
    } else {
      const data = await res.json();

      if (data["session"]) {
        setStatus("Redirecting...");
        redirect(data["session"]);
      } else {
        setTitle(`Connect ${data["client"].name}`);
        setSubtitle(`Via ${userinfo?.displayName}`);
        setClient(data["client"]);
        setLoading(false);
      }
    }
  }

  function decline() {
    if (window.history.length > 0) {
      window.history.back();
    } else {
      window.close();
    }
  }

  async function approve() {
    setLoading(true);
    setStatus("Approving...");

    const res = await request("/api/auth/o/connect?" + new URLSearchParams({
      client_id: searchParams["client_id"] as string,
      redirect_uri: encodeURIComponent(searchParams["redirect_uri"] as string),
      response_type: "code",
      scope: searchParams["scope"] as string
    }), {
      method: "POST",
      headers: { "Authorization": `Bearer ${getAtk()}` }
    });

    if (res.status !== 200) {
      setError(await res.text());
      setLoading(false);
    } else {
      const data = await res.json();
      setStatus("Redirecting...");
      setTimeout(() => redirect(data["session"]), 1850);
    }
  }

  function redirect(session: any) {
    const url = `${searchParams["redirect_uri"]}?code=${session["grant_token"]}&state=${searchParams["state"]}`;
    window.open(url, "_self");
  }

  preConnect();

  return (
    <div class="h-full flex justify-center items-center mx-5">
      <div class="card w-screen max-w-[480px] shadow-xl">
        <div class="card-body">
          <div id="header" class="text-center mb-5">
            <h1 class="text-xl font-bold">{title()}</h1>
            <p>{subtitle()}</p>
          </div>

          <Show when={error()}>
            <div id="alerts" class="mt-1">
              <div role="alert" class="alert alert-error">
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none"
                     viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span class="capitalize">{error()}</span>
              </div>
            </div>
          </Show>

          <Show when={loading()}>
            <div class="py-16 text-center">
              <div class="text-center">
                <div>
                  <span class="loading loading-lg loading-bars"></span>
                </div>
                <span>{status()}</span>
              </div>
            </div>
          </Show>

          <Show when={!loading()}>
            <div class="mb-3">
              <h2 class="font-bold">About who you connecting to</h2>
              <p>{client().description}</p>
            </div>
            <div class="mb-3">
              <h2 class="font-bold">Make sure you trust them</h2>
              <p>You may share your personal information after connect them. Learn about their privacy policy and user
                agreement to keep your personal information in safe.</p>
            </div>
            <div class="mb-5">
              <h2 class="font-bold">After approve this request</h2>
              <p>
                You will be redirect to{" "}
                <span class="link link-primary cursor-not-allowed">{searchParams["redirect_uri"]}</span>
              </p>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2">
              <button class="btn btn-accent" onClick={() => decline()}>Decline</button>
              <button class="btn btn-primary" onClick={() => approve()}>Approve</button>
            </div>
          </Show>
        </div>
      </div>
    </div>
  );
}

// pkg/views/src/views/auth/connect.vue
<template>
  <v-container class="h-screen flex flex-col gap-3 items-center justify-center">
    <v-card class="w-full max-w-[720px]" :loading="loading">
      <v-card-text class="card-grid pa-9">
        <div>
          <v-avatar color="accent" icon="mdi-connection" size="large" class="card-rounded mb-2" />
          <h1 class="text-2xl">Connect to third-party</h1>
          <p>One Solarpass, entire internet.</p>
        </div>

        <v-window :model-value="panel" class="pa-2 mx-[-0.5rem]">
          <v-window-item value="confirm">
            <div class="flex flex-col gap-2">
              <v-expand-transition>
                <v-alert v-show="error" variant="tonal" type="error" class="text-xs mb-3">
                  <p>Something went wrong... {{ error }}</p>
                  <br />

                  <p class="font-bold">
                    It's usually not our fault. Try bringing this link to give feedback to the developer of the app you
                    came from.
                  </p>
                </v-alert>
              </v-expand-transition>

              <div v-if="!error">
                <h1 class="font-bold text-xl">{{ metadata?.name ?? "Loading" }}</h1>
                <p>{{ metadata?.description ?? "Hold on a second please!" }}</p>

                <div class="mt-3">
                  <p class="opacity-80 text-xs">Permissions they requested</p>
                  <v-card variant="tonal" class="mt-1 mx-[-4px]">
                    <v-list density="compact">
                      <v-list-item v-for="claim in requestedClaims" lines="two">
                        <template #title>
                          <span class="capitalize">{{ getClaimDescription(claim)?.name }}</span>
                        </template>
                        <template #subtitle>
                          <span>{{ getClaimDescription(claim)?.description }}</span>
                        </template>
                        <template #prepend>
                          <v-icon :icon="getClaimDescription(claim)?.icon" size="x-large" />
                        </template>
                      </v-list-item>
                    </v-list>
                  </v-card>

                  <div class="mt-5 flex justify-between">
                    <v-btn prepend-icon="mdi-close" variant="text" color="error" :disabled="loading" @click="decline">
                      Decline
                    </v-btn>
                    <v-btn append-icon="mdi-check" variant="tonal" color="success" :disabled="loading" @click="approve">
                      Approve
                    </v-btn>
                  </div>

                  <div class="mt-5 text-xs text-center opacity-75">
                    <p>After approve their request, you will be redirect to</p>
                    <p class="text-mono">{{ route.query["redirect_uri"] }}</p>
                  </div>
                </div>
              </div>
            </div>
          </v-window-item>

          <v-window-item value="callback">
            <div>
              <v-icon icon="mdi-fire" size="32" color="grey-darken-3" class="mb-3" />

              <h1 class="font-bold text-xl">Authoirzed</h1>
              <p>You're done! We sucessfully established connection between you and {{ metadata?.name }}.</p>

              <p class="mt-3">Now you can continue your their app, we will redirect you soon.</p>

              <p class="mt-3">Teleporting you to...</p>
              <p class="text-xs text-mono">{{ route.query["redirect_uri"] }}</p>
            </div>
          </v-window-item>
        </v-window>
      </v-card-text>
    </v-card>

    <copyright />
  </v-container>
</template>

<script setup lang="ts">
import { computed, ref } from "vue"
import { useRoute } from "vue-router"
import { request } from "@/scripts/request"
import { getAtk } from "@/stores/userinfo"
import { claims, type ClaimType } from "@/views/auth/claims"
import Copyright from "@/components/Copyright.vue"

const route = useRoute()

const error = ref<string | null>(null)

const loading = ref(false)

const metadata = ref<any>(null)
const requestedClaims = computed(() => {
  const scope: string = (route.query["scope"] as string) ?? ""
  return scope.split(" ")
})

const panel = ref("confirm")

async function preconnect() {
  const res = await request(`/api/auth/o/connect${location.search}`, {
    headers: { Authorization: `Bearer ${getAtk()}` },
  })

  if (res.status !== 200) {
    error.value = await res.text()
  } else {
    const data = await res.json()

    if (data["session"]) {
      panel.value = "callback"
      callback(data["session"])
    } else {
      metadata.value = data["client"]
      loading.value = false
    }
  }
}

preconnect()

function decline() {
  if (window.history.length > 0) {
    window.history.back()
  } else {
    window.close()
  }
}

async function approve() {
  loading.value = true
  const res = await request(
    "/api/auth/o/connect?" +
      new URLSearchParams({
        client_id: route.query["client_id"] as string,
        redirect_uri: encodeURIComponent(route.query["redirect_uri"] as string),
        response_type: "code",
        scope: route.query["scope"] as string,
      }),
    {
      method: "POST",
      headers: { Authorization: `Bearer ${getAtk()}` },
    },
  )

  if (res.status !== 200) {
    error.value = await res.text()
    loading.value = false
  } else {
    const data = await res.json()
    panel.value = "callback"
    setTimeout(() => callback(data["session"]), 1850)
  }
}

function callback(session: any) {
  const url = `${route.query["redirect_uri"]}?code=${session["grant_token"]}&state=${route.query["state"]}`
  window.open(url, "_self")
}

function getClaimDescription(key: string): ClaimType {
  return claims.hasOwnProperty(key) ? claims[key] : { icon: "mdi-asterisk", name: key, description: "Unknown claim..." }
}
</script>

<style scoped>
.card-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}

@media (max-width: 768px) {
  .card-grid {
    grid-template-columns: 1fr;
  }
}

.card-rounded {
  border-radius: 8px;
}
</style>
