// pkg/views/src/views/security.vue
<template>
  <div>
    <v-expansion-panels>
      <v-expansion-panel eager title="Challenges">
        <template #text>
          <v-card :loading="reverting.challenges" variant="outlined">
            <v-data-table-server
              density="compact"
              :headers="dataDefinitions.challenges"
              :items="challenges"
              :items-length="pagination.challenges.total"
              :loading="reverting.challenges"
              v-model:items-per-page="pagination.challenges.pageSize"
              @update:options="readChallenges"
              item-value="id"
            >
              <template v-slot:item="{ item }: { item: any }">
                <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.ip_address }}</td>
                  <td>
                    <v-tooltip :text="item.user_agent" location="top">
                      <template #activator="{ props }">
                        <div v-bind="props" class="text-ellipsis whitespace-nowrap overflow-hidden max-w-[280px]">
                          {{ item.user_agent }}
                        </div>
                      </template>
                    </v-tooltip>
                  </td>
                  <td>{{ new Date(item.created_at).toLocaleString() }}</td>
                </tr>
              </template>
            </v-data-table-server>
          </v-card>
        </template>
      </v-expansion-panel>

      <v-expansion-panel eager title="Sessions">
        <template #text>
          <v-card :loading="reverting.sessions" variant="outlined">
            <v-data-table-server
              density="compact"
              :headers="dataDefinitions.sessions"
              :items="sessions"
              :items-length="pagination.sessions.total"
              :loading="reverting.sessions"
              v-model:items-per-page="pagination.sessions.pageSize"
              @update:options="readSessions"
              item-value="id"
            >
              <template v-slot:item="{ item }: { item: any }">
                <tr>
                  <td>{{ item.id }}</td>
                  <td>
                    <v-chip v-for="value in item.audiences" size="x-small" color="warning" class="capitalize">
                      {{ value }}
                    </v-chip>
                  </td>
                  <td>
                    <v-chip v-for="value in item.claims" size="x-small" color="info" class="font-mono">
                      {{ value }}
                    </v-chip>
                  </td>
                  <td>{{ new Date(item.created_at).toLocaleString() }}</td>
                  <td>
                    <v-tooltip text="Sign out">
                      <template #activator="{ props }">
                        <v-btn
                          v-bind="props"
                          variant="text"
                          size="x-small"
                          color="error"
                          icon="mdi-logout-variant"
                          @click="killSession(item)"
                        />
                      </template>
                    </v-tooltip>
                  </td>
                </tr>
              </template>
            </v-data-table-server>
          </v-card>
        </template>
      </v-expansion-panel>

      <v-expansion-panel eager title="Events">
        <template #text>
          <v-card :loading="reverting.events" variant="outlined">
            <v-data-table-server
              density="compact"
              :headers="dataDefinitions.events"
              :items="events"
              :items-length="pagination.events.total"
              :loading="reverting.events"
              v-model:items-per-page="pagination.events.pageSize"
              @update:options="readEvents"
              item-value="id"
            >
              <template v-slot:item="{ item }: { item: any }">
                <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.type }}</td>
                  <td>{{ item.target }}</td>
                  <td>{{ item.ip_address }}</td>
                  <td>
                    <v-tooltip :text="item.user_agent" location="top">
                      <template #activator="{ props }">
                        <div v-bind="props" class="text-ellipsis whitespace-nowrap overflow-hidden max-w-[280px]">
                          {{ item.user_agent }}
                        </div>
                      </template>
                    </v-tooltip>
                  </td>
                  <td>{{ new Date(item.created_at).toLocaleString() }}</td>
                </tr>
              </template>
            </v-data-table-server>
          </v-card>
        </template>
      </v-expansion-panel>
    </v-expansion-panels>
  </div>
</template>

<script setup lang="ts">
import { request } from "@/scripts/request"
import { getAtk, useUserinfo } from "@/stores/userinfo"
import { reactive, ref } from "vue"

const id = useUserinfo()

const error = ref<string | null>(null)

const dataDefinitions: { [id: string]: any[] } = {
  challenges: [
    { align: "start", key: "id", title: "ID" },
    { align: "start", key: "ip_address", title: "IP Address" },
    { align: "start", key: "user_agent", title: "User Agent" },
    { align: "start", key: "created_at", title: "Issued At" },
  ],
  sessions: [
    { align: "start", key: "id", title: "ID" },
    { align: "start", key: "audiences", title: "Audiences" },
    { align: "start", key: "claims", title: "Claims" },
    { align: "start", key: "created_at", title: "Issued At" },
    { align: "start", key: "actions", title: "Actions", sortable: false },
  ],
  events: [
    { align: "start", key: "id", title: "ID" },
    { align: "start", key: "type", title: "Type" },
    { align: "start", key: "target", title: "Affected Object" },
    { align: "start", key: "ip_address", title: "IP Address" },
    { align: "start", key: "user_agent", title: "User Agent" },
    { align: "start", key: "created_at", title: "Performed At" },
  ],
}

const challenges = ref<any>([])
const sessions = ref<any>([])
const events = ref<any>([])

const reverting = reactive({ challenges: false, sessions: false, events: false })
const pagination = reactive({
  challenges: { page: 1, pageSize: 5, total: 0 },
  sessions: { page: 1, pageSize: 5, total: 0 },
  events: { page: 1, pageSize: 5, total: 0 },
})

async function readChallenges({ page, itemsPerPage }: { page?: number; itemsPerPage?: number }) {
  if (itemsPerPage) pagination.challenges.pageSize = itemsPerPage
  if (page) pagination.challenges.page = page

  reverting.challenges = true
  const res = await request(
    "/api/users/me/challenges?" +
      new URLSearchParams({
        take: pagination.challenges.pageSize.toString(),
        offset: ((pagination.challenges.page - 1) * pagination.challenges.pageSize).toString(),
      }),
    {
      headers: { Authorization: `Bearer ${getAtk()}` },
    },
  )
  if (res.status !== 200) {
    error.value = await res.text()
  } else {
    const data = await res.json()
    challenges.value = data["data"]
    pagination.challenges.total = data["count"]
  }
  reverting.challenges = false
}

async function readSessions({ page, itemsPerPage }: { page?: number; itemsPerPage?: number }) {
  if (itemsPerPage) pagination.sessions.pageSize = itemsPerPage
  if (page) pagination.sessions.page = page

  reverting.sessions = true
  const res = await request(
    "/api/users/me/sessions?" +
      new URLSearchParams({
        take: pagination.sessions.pageSize.toString(),
        offset: ((pagination.sessions.page - 1) * pagination.sessions.pageSize).toString(),
      }),
    {
      headers: { Authorization: `Bearer ${getAtk()}` },
    },
  )
  if (res.status !== 200) {
    error.value = await res.text()
  } else {
    const data = await res.json()
    sessions.value = data["data"]
    pagination.sessions.total = data["count"]
  }
  reverting.sessions = false
}

async function readEvents({ page, itemsPerPage }: { page?: number; itemsPerPage?: number }) {
  if (itemsPerPage) pagination.events.pageSize = itemsPerPage
  if (page) pagination.events.page = page

  reverting.events = true
  const res = await request(
    "/api/users/me/events?" +
      new URLSearchParams({
        take: pagination.events.pageSize.toString(),
        offset: ((pagination.events.page - 1) * pagination.events.pageSize).toString(),
      }),
    {
      headers: { Authorization: `Bearer ${getAtk()}` },
    },
  )
  if (res.status !== 200) {
    error.value = await res.text()
  } else {
    const data = await res.json()
    events.value = data["data"]
    pagination.events.total = data["count"]
  }
  reverting.events = false
}

Promise.all([readChallenges({}), readSessions({}), readEvents({})])

async function killSession(item: any) {
  reverting.sessions = true
  const res = await request(`/api/users/me/sessions/${item.id}`, {
    method: "DELETE",
    headers: { Authorization: `Bearer ${getAtk()}` },
  })
  if (res.status !== 200) {
    error.value = await res.text()
  } else {
    await readSessions({})
    error.value = null
  }
  reverting.sessions = false
}
</script>

<style>
.rounded-card {
  border-radius: 8px;
}
</style>

// pkg/views/src/pages/users/security.tsx
import {
  Alert,
  Box,
  Card,
  CardContent,
  Collapse,
  Container,
  Grid,
  LinearProgress,
  Tab,
  Tabs,
  Typography
} from "@mui/material";
import { useUserinfo } from "@/stores/userinfo.tsx";
import { TabContext, TabPanel } from "@mui/lab";
import { useEffect, useState } from "react";
import { DataGrid, GridActionsCellItem, GridColDef, GridRowParams, GridValueGetterParams } from "@mui/x-data-grid";
import { request } from "@/scripts/request.ts";
import ExitToAppIcon from "@mui/icons-material/ExitToApp";


export function Component() {
  const dataDefinitions: { [id: string]: GridColDef[] } = {
    challenges: [
      { field: "id", headerName: "ID", width: 64 },
      { field: "ip_address", headerName: "IP Address", minWidth: 128 },
      { field: "user_agent", headerName: "User Agent", minWidth: 320 },
      {
        field: "created_at",
        headerName: "Issued At",
        minWidth: 160,
        valueGetter: (params: GridValueGetterParams) => new Date(params.row.created_at).toLocaleString()
      }
    ],
    sessions: [
      { field: "id", headerName: "ID", width: 64 },
      {
        field: "audiences",
        headerName: "Audiences",
        minWidth: 128,
        valueGetter: (params: GridValueGetterParams) => params.row.audiences.join(", ")
      },
      {
        field: "claims",
        headerName: "Claims",
        minWidth: 224,
        valueGetter: (params: GridValueGetterParams) => params.row.claims.join(", ")
      },
      {
        field: "created_at",
        headerName: "Issued At",
        minWidth: 160,
        valueGetter: (params: GridValueGetterParams) => new Date(params.row.created_at).toLocaleString()
      },
      {
        field: "actions",
        type: "actions",
        getActions: (params: GridRowParams) => [
          <GridActionsCellItem
            icon={<ExitToAppIcon />}
            onClick={() => killSession(params.row)}
            disabled={loading}
            label="Sign Out"
          />
        ]
      }
    ],
    events: [
      { field: "id", headerName: "ID", width: 64 },
      { field: "type", headerName: "Type", minWidth: 128 },
      { field: "target", headerName: "Affected Object", minWidth: 128 },
      { field: "ip_address", headerName: "IP Address", minWidth: 128 },
      { field: "user_agent", headerName: "User Agent", minWidth: 128 },
      {
        field: "created_at",
        headerName: "Performed At",
        minWidth: 160,
        valueGetter: (params: GridValueGetterParams) => new Date(params.row.created_at).toLocaleString()
      }
    ]
  };

  const { getAtk } = useUserinfo();

  const [challenges, setChallenges] = useState<any[]>([]);
  const [challengeCount, setChallengeCount] = useState(0);
  const [sessions, setSessions] = useState<any[]>([]);
  const [sessionCount, setSessionCount] = useState(0);
  const [events, setEvents] = useState<any[]>([]);
  const [eventCount, setEventCount] = useState(0);

  const [pagination, setPagination] = useState({
    challenges: { page: 0, pageSize: 5 },
    sessions: { page: 0, pageSize: 5 },
    events: { page: 0, pageSize: 5 }
  });

  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [reverting] = useState({
    challenges: true,
    sessions: true,
    events: true
  });

  const [dataPane, setDataPane] = useState("challenges");

  async function readChallenges() {
    reverting.challenges = true;
    const res = await request("/api/users/me/challenges?" + new URLSearchParams({
      take: pagination.challenges.pageSize.toString(),
      offset: (pagination.challenges.page * pagination.challenges.pageSize).toString()
    }), {
      headers: { Authorization: `Bearer ${getAtk()}` }
    });
    if (res.status !== 200) {
      setError(await res.text());
    } else {
      const data = await res.json();
      setChallenges(data["data"]);
      setChallengeCount(data["count"]);
    }
    reverting.challenges = false;
  }

  async function readSessions() {
    reverting.sessions = true;
    const res = await request("/api/users/me/sessions?" + new URLSearchParams({
      take: pagination.sessions.pageSize.toString(),
      offset: (pagination.sessions.page * pagination.sessions.pageSize).toString()
    }), {
      headers: { Authorization: `Bearer ${getAtk()}` }
    });
    if (res.status !== 200) {
      setError(await res.text());
    } else {
      const data = await res.json();
      setSessions(data["data"]);
      setSessionCount(data["count"]);
    }
    reverting.sessions = false;
  }

  async function readEvents() {
    reverting.events = true;
    const res = await request("/api/users/me/events?" + new URLSearchParams({
      take: pagination.events.pageSize.toString(),
      offset: (pagination.events.page * pagination.events.pageSize).toString()
    }), {
      headers: { Authorization: `Bearer ${getAtk()}` }
    });
    if (res.status !== 200) {
      setError(await res.text());
    } else {
      const data = await res.json();
      setEvents(data["data"]);
      setEventCount(data["count"]);
    }
    reverting.events = false;
  }

  async function killSession(item: any) {
    setLoading(true);
    const res = await request(`/api/users/me/sessions/${item.id}`, {
      method: "DELETE",
      headers: { Authorization: `Bearer ${getAtk()}` }
    });
    if (res.status !== 200) {
      setError(await res.text());
    } else {
      await readSessions();
      setError(null);
    }
    setLoading(false);
  }

  useEffect(() => {
    readChallenges().then(() => console.log("Refreshed challenges list."));
  }, [pagination.challenges]);

  useEffect(() => {
    readSessions().then(() => console.log("Refreshed sessions list."));
  }, [pagination.sessions]);

  useEffect(() => {
    readEvents().then(() => console.log("Refreshed events list."));
  }, [pagination.events]);

  return (
    <Container sx={{ pt: 5 }} maxWidth="md">
      <Box sx={{ px: 3 }}>
        <Typography variant="h5">Security</Typography>
        <Typography variant="body2">
          Overview and control all security details in your account.
        </Typography>
      </Box>

      <Collapse in={error != null}>
        <Alert severity="error" className="capitalize" sx={{ mt: 1.5 }}>{error}</Alert>
      </Collapse>

      <Grid container>
        <Grid item xs={12}>
          <Box sx={{ mt: 2 }}>
            <Card variant="outlined">
              <Collapse in={loading}>
                <LinearProgress />
              </Collapse>

              <TabContext value={dataPane}>
                <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
                  <Tabs centered value={dataPane} onChange={(_, val) => setDataPane(val)}>
                    <Tab label="Challenges" value="challenges" />
                    <Tab label="Sessions" value="sessions" />
                    <Tab label="Events" value="events" />
                  </Tabs>
                </Box>

                <CardContent style={{ padding: "20px 24px" }}>
                  <TabPanel value={"challenges"}>
                    <DataGrid
                      pageSizeOptions={[5, 10, 15, 20, 25]}
                      paginationMode="server"
                      loading={reverting.challenges}
                      rows={challenges}
                      rowCount={challengeCount}
                      columns={dataDefinitions.challenges}
                      paginationModel={pagination.challenges}
                      onPaginationModelChange={(val) => setPagination({ ...pagination, challenges: val })}
                      checkboxSelection
                    />
                  </TabPanel>
                  <TabPanel value={"sessions"}>
                    <DataGrid
                      pageSizeOptions={[5, 10, 15, 20, 25]}
                      paginationMode="server"
                      loading={reverting.sessions}
                      rows={sessions}
                      rowCount={sessionCount}
                      columns={dataDefinitions.sessions}
                      paginationModel={pagination.sessions}
                      onPaginationModelChange={(val) => setPagination({ ...pagination, sessions: val })}
                      checkboxSelection
                    />
                  </TabPanel>
                  <TabPanel value={"events"}>
                    <DataGrid
                      pageSizeOptions={[5, 10, 15, 20, 25]}
                      paginationMode="server"
                      loading={reverting.events}
                      rows={events}
                      rowCount={eventCount}
                      columns={dataDefinitions.events}
                      paginationModel={pagination.events}
                      onPaginationModelChange={(val) => setPagination({ ...pagination, events: val })}
                      checkboxSelection
                    />
                  </TabPanel>
                </CardContent>
              </TabContext>
            </Card>
          </Box>
        </Grid>
      </Grid>
    </Container>
  );
}
